// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member.sql

package query

import (
	"context"

	"study/internal/feature/member"
	"study/internal/shared/model"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (
    email,
    password,
    name,
    status
) VALUES (
    $1, $2, $3, $4
)
RETURNING member_id
`

type CreateMemberParams struct {
	Email    string
	Password string
	Name     string
	Status   model.Status
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Status,
	)
	var member_id int64
	err := row.Scan(&member_id)
	return member_id, err
}

const findMemberByEmail = `-- name: FindMemberByEmail :one
SELECT
    member_id,
    email,
    password,
    name,
    tel,
    address,
    profile,
    status,
    created_at,
    updated_at,
    deleted_at
FROM members
WHERE email = $1
`

func (q *Queries) FindMemberByEmail(ctx context.Context, email string) (Member, error) {
	row := q.db.QueryRow(ctx, findMemberByEmail, email)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Tel,
		&i.Address,
		&i.Profile,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findMemberByID = `-- name: FindMemberByID :one
SELECT
    member_id,
    email,
    password,
    name,
    tel,
    address,
    profile,
    status,
    created_at,
    updated_at,
    deleted_at
FROM members
WHERE member_id = $1
`

func (q *Queries) FindMemberByID(ctx context.Context, memberID int64) (Member, error) {
	row := q.db.QueryRow(ctx, findMemberByID, memberID)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Tel,
		&i.Address,
		&i.Profile,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRolesByMemberID = `-- name: GetRolesByMemberID :many
SELECT role
FROM member_roles
WHERE member_id = $1
`

func (q *Queries) GetRolesByMemberID(ctx context.Context, memberID int64) ([]member.Role, error) {
	rows, err := q.db.Query(ctx, getRolesByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []member.Role
	for rows.Next() {
		var role member.Role
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMemberRole = `-- name: InsertMemberRole :exec
INSERT INTO member_roles (
    member_id,
    role
) VALUES (
    $1, $2
)
`

type InsertMemberRoleParams struct {
	MemberID int64
	Role     member.Role
}

func (q *Queries) InsertMemberRole(ctx context.Context, arg InsertMemberRoleParams) error {
	_, err := q.db.Exec(ctx, insertMemberRole, arg.MemberID, arg.Role)
	return err
}
