// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
	"study/internal/feature/member"
	"study/internal/shared/model"
)

type Member struct {
	MemberID  int64
	Email     string
	Password  string
	Name      string
	Tel       pgtype.Text
	Address   pgtype.Text
	Profile   pgtype.Text
	Status    model.Status
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type MemberRole struct {
	MemberRoleID int64
	MemberID     int64
	Role         member.Role
}
